# version: '3.8'

services:
  phrasesDB:
    image: postgres:15.3
    container_name: phrases
    restart: always 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: next-postgre-app
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@phrasesDB:5432/${DB_NAME}
    depends_on:
      - phrasesDB
    volumes:
      - .:/app
      - /app/node_modules
